spring:
  application:
    name: lapzone-api


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080 }
  error:
    include-message: always
app:
  jwt:
    secret: "lapzone-super-secret-key-para-firmar-tokens-jwt-cambiar-despues"
    expiration-ms: ${ JWT_EXPIRATION_MS:86400000 }
  frontend-url: ${APP_FRONTEND_URL:http://localhost:5173}
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}